version: '3'
services:
  api_gateway:
    image: nginx
    container_name: api_gateway
    ports:
      - '80:80'
      - '443:443'
    networks:
      - event-publisher
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  event-publisher:
    build:
      context: .
      target: dev
      dockerfile: apps/event-publisher/Dockerfile
      args:
        - TAG=event-publisher:1.0
    image: event-publisher:1.0
    container_name: event-publisher
    networks:
      - event-publisher
    environment:
      EVENT_PUBLISHER_PORT: 2222
      KAFKA_CLIENT_ID: event-publisher
      KAFKA_BROKERS: 'kafka-1:9092,kafka-2:9093'
    depends_on:
      - api_gateway
      - kafka-1
      - kafka-2

  student_postgres:
    image: postgres
    container_name: student_database
    ports:
      - '5440:5432'
    env_file:
      - student.env
    networks:
      - student
    volumes:
      - studentDb:/var/lib/postgresql/data

  school_postgres:
    image: postgres
    container_name: school_database
    ports:
      - '5441:5432'
    env_file:
      - school.env
    networks:
      - school
    volumes:
      - schoolDB:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - event-publisher
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-1:
    image: confluentinc/cp-kafka
    container_name: kafka-1
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    networks:
      - event-publisher
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-2:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    container_name: kafka-2
    ports:
      - 39092:39092
    networks:
      - event-publisher
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  student:
    driver: bridge
  school:
    driver: bridge
  event-publisher:
    driver: bridge

volumes:
  studentDb:
    driver: local
  schoolDB:
    driver: local
