version: '3'
services:
  user_postgres:
    image: postgres
    container_name: user_database
    ports:
      - '5440:5432'
    env_file:
      - docker.env
    networks:
      - user
    volumes:
      - db:/var/lib/postgresql/data

  school_postgres:
    image: postgres
    container_name: school_database
    ports:
      - '5441:5432'
    env_file:
      - docker.env
    networks:
      - school
    volumes:
      - schoolDB:/var/lib/postgresql/data

networks:
  user:
    driver: bridge
  school:
    driver: bridge

volumes:
  db:
    driver: local
  schoolDB:
    driver: local
