version: '3'
services:
  student_postgres:
    image: postgres
    container_name: student_database
    ports:
      - '5440:5432'
    env_file:
      - student.env
    networks:
      - student
    volumes:
      - studentDb:/var/lib/postgresql/data

  school_postgres:
    image: postgres
    container_name: school_database
    ports:
      - '5441:5432'
    env_file:
      - school.env
    networks:
      - school
    volumes:
      - schoolDB:/var/lib/postgresql/data

networks:
  student:
    driver: bridge
  school:
    driver: bridge

volumes:
  studentDb:
    driver: local
  schoolDB:
    driver: local
